language: scala
scala:
  - 2.12.8
jdk:
  - openjdk10
services:
  - docker
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
env:
  - AWS_ACCESS_KEY=x AWS_SECRET_KEY=x AWS_CBOR_DISABLE=true
before_script:
  - ./localstack.sh
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile flowLintLib test doc
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
branches:
  only:
    - master
